version: "3"

services:
    server:
        build:
            context: .
            dockerfile: server/Dockerfile
        ports:
          - "2224:2224"
        volumes:
          - ./server:/go/src/github.com/noreng-jg/sshserver


